const BASE_URL = 'https://app.alomdabasha.com/api/';
const Register_VAR = "register";
const Login_VAR = "login";
const Active_Code = "active_code";
const USER_PROFILE = "User_profile";
const UPDATE_PASSWORD = "update_password";
const Resend_Active_Code ="resend_active_code";
const Check_Code ="check_code";
const Check_Email ="check_email";
const Store_Contact_Us ="contact/send";
const User_Profile_Update = "User_profile/update";
const home_markters_superMarkters = "home";
const Filter_Service = "filter-service";
const Show_Service = "show-service";
const Add_To_Cart = "add-to-cart";
const Update_And_Delete_cart = "update-to-cart";
//const Apdate_All_Cart_Items = "show-cart";
const Show_cart = "show-service";
const Store_Order = "store-order";
const Show_All_Marketer_Orders = "show-all-marketer-orders";
const Show_Order = "show-order";
const Send_Money_Request = "send-money-request";
const Show_All_Marketers = "show-all-marketers";
const Show_Package_Marketers = "show-package-marketers";
const Show_Cart = "show-cart";
const Countery_And_City = "countrys/show";
const Update_All_Cart_Items = "update-all-cart";
const Show_New_Delegates_Orders = "show-new-delegates_orders";
const Send_Transfer = "send-transfer";
const Show_Services = "show-services";
const Send_Service_Request = "send-service-request";
const Show_Delegate_Order = "show-delegate_order";
const Update_Order = "update-order";
const Change_Order_Status = "change-order-status";
const Show_All_Delegates_Orders = "show-all-delegates-orders";
const Delegate_Finish_Order = "delegate-finish-order";
const log_Out = "logout";
const Packages_Show = "packages/show";
const Packages_Markters_Show = "show-package-marketers";
const Store_Gifts = "store-gifts";
const Device_Firebase_Token = "update/device_id";
const All_Notification_Show = "all-notification/show";
const Dotification_Delete = "notification/delete";
const UpdateOrder = "update-order";
const SHOWSERVICE = "show-services";
const UPDATEORDERMarkter = "update-order";
const RESENDORDER = "resend-order";
// const Delegate_Finish_Order = "delegate-finish-order";




// Headers
const FIRE_BASE_TOKEN_HEADER = 'FirebaseToken';
const PLATFORM_HEADER = 'Platform';
const CONTENT_TYPE_HEADER = 'Content-Type';
const LANG_HEADER = 'Lang';
const AUTH_HEADER = 'Auth';
const Country_HEADER = 'Country';